### join
POST http://localhost:8080/api/member
Content-Type: application/json

{
  "email" : "wogud222@test.com",
  "password" : "1234"
}


### login
POST http://localhost:8080/api/login
Content-Type: application/json

{
"email" : "wogud222@test.com",
"password" : "1234"
}

<> 2024-11-01T095555.200.json



### modify password
PATCH http://localhost:8080/api/member/password
Content-Type: application/json

{
"email" : "wogud222@test.com",
"password" : "1234"
}